### ISSUE TITLE
JSON parsing error with schema

### ISSUE THREAD

**Issue by YuriOsokin** [decatur/ansatz27#5]
The documents is parsed successfully without a schema. With the schema, the document is successfully validated using the [JSON schema validator](http://jsonschemalint.com/draft4/#). However, using the script, JSON_Parser.m shows "Illegal token" error.
The JSON file and its schema are attached.

[Parameters.txt](https://github.com/decatur/ansatz27/files/316074/Parameters.txt)
[ParametersSchema.txt](https://github.com/decatur/ansatz27/files/316075/ParametersSchema.txt)

**Comment by decatur** [comment]
Usage of `allOf` with more than one schema may fail if first schema validates.
